services:
  web:
    build:
      context: /home/jiahaolin/repositorios/HLC/jiaHaoHLC/docker/caronte/
      dockerfile: ./dockerfiles/base/ubbase 
      args: #Variables de DFILE para la construcci√≥n de las imagenes 
        - USUARIO=jiahaolinwu
    container_name: ctbase