services:
  web:
    build:
      context: 
      dockerfile: ./dockerfiles/base/ubbase 
     # args: #Variables de DFILE para la construcci√≥n de las imagenes 
     #   - USUARIO=jiahaolin
    container_name: ctbase
    # environment:
    #   - USUARIO=jiahao
    #   - PASSWORD=1234
    env_file:
      - ./.env
    volumes:
      - ./logs:/root/logs