services:
  web:
    build:
      context: /home/jiahaolin/jiahaohlc/docker/caronte #${CONTEXTO}
      dockerfile: ./dockerfiles/miportfolio/miporfolio
      args:
        - PROYECTO=./proyecto/miportfolio/src/ #${PROYECTO}
    container_name: ctportfolio
    ports:
      - "6969:80" #${PORT_WEB}
    env_file:
      - ./.env
