services:
  web:
    build:
      context: /home/jiahaolin/jiahaohlc/docker/caronte/
      dockerfile: ./dockerfiles/base/ubbase 
      args: #Variables de DFILE para la construcci√≥n de las imagenes 
        - USUARIO=jiahao
    container_name: ${CONTAINER_NAME}
    # environment:
    #   - USUARIO=jiahao
    #   - PASSWORD=1234
    ports:
      - ${PORT_SSH}:${PORT_SSH}
    env_file:
      - ./.env
    volumes:
      - ./logs:/root/logs 
    networks:
      netcaronte:
        ipv4_address: ${IP_WEB}
networks:
  netcaronte:
  driver: bridge
  ipam:
    driver: default
    config:
      - subnet: ${SUBNET}

