services:
  web:
    build:
      context: ${CONTEXTO}
      dockerfile: ./dockerfiles/sweb/nginx/nginx
    container_name: ${NOMBRE}
    ports:
      - "${PORT_WEB}:80"     
    env_file:
      - ./.env
    image: jiahaolin69/nginxclase
    volumes:
      - ./logs:/root/logs      
    networks:
      netnginxclase:
        ipv4_address: ${IP}
networks:
  netnginxclase:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET}