services:
  web-taller:
    build: 
      context: ..
      dockerfile: ./build img/dockerfile
      args:
        - PROYECTO=${PROYECTO}
        - USUARIO=${USUARIO}
        - TIPO=${TIPO}
    container_name: web_taller
    image: jiahaolin69/webtallerclase
    hostname: web_taller
    ports:
      - "80:80"
    env_file:
      - ./.env
    