services:
  webtaller:
    build: 
      context: .
      dockerfile: ./dockerfile
    container_name: web_taller
    args:
      - PROYECTO=${PROYECTO}
      - USUARIO=${USUARIO}
      - TIPO=${TIPO}
    image: jiahaolin69/webtallerclase
    hostname: web_taller
    env_file:
      - ./.env
    