services:
    build: 
      context: ..
      dockerfile: ./deploy/dockerfile
      args:
        - PROYECTO=${PROYECTO}
        - USUARIO=${USUARIO}
        - TIPO=${TIPO}
    container_name: web_taller
    image: jiahaolin69/webtallerclase
    hostname: web_taller
    env_file:
      - ./.env
    