services:
  web:
    build:
      context: ${CONTEXTO}
      dockerfile: ./dockerfiles/node/node
    container_name: nodeclase
    ports:
      - "8888:78"   
    env_file:
      - ./.env
    image: jiahaolin69/nodejsclase
    volumes:
      - ./logs:/root/logs      
      - ../pmegacrossover/Web-Practica1-JiaHao:/root/admin/node/proyectos/pmegacrossover
    networks:
      netnodeclase:
        ipv4_address: ${IP}
networks:
  netnodeclase:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET}