apiVersion: apps/v1
kind: Deployment 
metadata:
  name: webtaller-deployment
  namespace: proyectotaller
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webtaller
  template:
    metadata:
      labels:
        app: webtaller
    spec:
      containers:
      - name: webtaller
        image: jiahaolin69/webtallerclase
        ports:
        - containerPort: 80