apiVersion: apps/v1
kind: Deployment 
metadata:
  name: webportfolio-deployment
  namespace: proyectoportfolio
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webportfolio
  template:
    metadata:
      labels:
        app: webportfolio
    spec:
      containers:
      - name: webportfolio
        image: jiahaolin69/miportfolio
        ports:
        - containerPort: 80