apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webtaller-ingress
  namespace: proyectoportfolio
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    # Hemos quitado el rewrite-target aqu√≠
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - portfolio.megacrossover.es
      secretName: portfolio-tls-prod
  rules:
    - host: portfolio.megacrossover.es
      http:
        paths:
          - path: /
            pathType: Prefix # Cambiado a Prefix para mayor compatibilidad
            backend:
              service:
                name: portfolio-taller
                port:
                  number: 80