apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webtaller-ingress
  namespace: proyectoportfolio
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    # BORRA O COMENTA LA L√çNEA DE REWRITE-TARGET
    # nginx.ingress.kubernetes.io/rewrite-target: / 
spec:
  tls:
    - hosts:
        - portfolio.megacrossover.es
      secretName: portfolio-tls-prod
  rules:
    - host: portfolio.megacrossover.es
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific # Cambiado para evitar conflictos de captura
            backend:
              service:
                name: portfolio-taller
                port:
                  number: 80