apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webportfolio-ingress
  namespace: proyectoportfolio
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    # ESTA L√çNEA ES CLAVE PARA EL ERROR 404:
    acme.cert-manager.io/http01-edit-in-place: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - portfolio.megacrossover.es
      secretName: portfolio-tls-prod
  rules:
    - host: portfolio.megacrossover.es
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: portfolio-taller
                port:
                  number: 80