apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webtaller-ingress
  namespace: proyectoportfolio
  annotations:
    # Se mantiene para compatibilidad, aunque se recomienda usar spec.ingressClassName
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx # Forma moderna de definir el controlador
  tls:
    - hosts:
        - portfolio.megacrossover.es
      secretName: portfolio-tls-prod
  rules:
    - host: portfolio.megacrossover.es
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: portfolio-taller
                port:
                  number: 80