apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webtaller-ingress
  namespace: proyectoportfolio
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: portfolio.megacrossover.es
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: portfolio-taller
            port:
              number: 80