apiVersion: v1
kind: Service
metadata:
  name: portfolio-taller
  namespace: proyectoportfolio
spec:
  type: NodePort
  selector:
    app: webportfolio
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30081